/**
 * Type definitions for the OpenCode Prompt Log Plugin
 * Defines data structures used for tracking conversation metadata and logging
 */

/**
 * Represents a single assistant message step within a session.
 * In agent workflows, multiple steps may complete within one session.
 */
export interface MessageStep {
  /** Step number within the session (1-based) */
  stepNumber: number;
  /** Unique identifier for this assistant message */
  messageID: string;
  /** Agent name for this step (e.g., 'oracle', 'build') */
  agent: string;
  /** Model used for this step (e.g., 'opencode/hy3-preview-free') */
  model: string;
  /** Formatted time string (HH:MM:SS) when this step completed */
  time: string;
  /** Duration of this step in seconds */
  duration: string;
  /** Input tokens consumed by this step */
  inputTokens: number;
  /** Output tokens generated by this step */
  outputTokens: number;
  /** Context tokens for this step */
  contextTokens: number;
  /** Cache read tokens for this step */
  cacheRead: number;
  /** Cache write tokens for this step */
  cacheWrite: number;
}

/**
 * Represents the state of a conversation session
 * Captured when user sends a message, stored until assistant response completes
 */
export interface SessionState {
  /** Unique identifier for the user's message in this session */
  userMsgID: string;
  /** The prompt/input text from the user */
  prompt: string;
  /** AI model identifier (e.g., 'opencode/hy3-preview-free') */
  model: string;
  /** Unix timestamp (ms) when the session started */
  startTime: number;
  /** Array of agent names representing the call chain (e.g., ['main', 'oracle', 'build']) */
  agentChain: string[];
  /** Date string in 'YYYY-MM-DD' format, used for file naming */
  sessionStartTime: string;
  /** Set of assistant message IDs that have already been processed, to avoid double-counting */
  completedMessageIDs: Set<string>;
  /** Accumulated input tokens across all assistant messages in this session */
  totalInputTokens: number;
  /** Accumulated output tokens across all assistant messages in this session */
  totalOutputTokens: number;
  /** Accumulated context tokens across all assistant messages in this session */
  totalContextTokens: number;
  /** Accumulated cache read tokens across all assistant messages in this session */
  totalCacheRead: number;
  /** Accumulated cache write tokens across all assistant messages in this session */
  totalCacheWrite: number;
  /** Model from the most recent assistant message (may differ from initial model in agent chains) */
  lastModel: string;
  /** Whether at least one assistant message has completed (used to avoid writing empty logs) */
  hasCompletedMessage: boolean;
  /** Number of completed steps so far */
  stepCount: number;
  /** Whether the file header has been written for this session */
  headerWritten: boolean;
}

/**
 * Represents the summary log entry for a completed session
 * Written when session.idle fires, after all step logs have been written
 */
export interface LogData {
  /** Unique session identifier */
  sessionID: string;
  /** Formatted time string (HH:MM:SS) when conversation started */
  time: string;
  /** Agent call chain as arrow-separated string (e.g., 'oracle → build → explore') */
  agentChain: string;
  /** AI model identifier used for this conversation */
  model: string;
  /** User's original prompt text */
  prompt: string;
  /** Duration of conversation processing in seconds (fixed to 2 decimal places) */
  duration: string;
  /** Number of completed steps in this session */
  steps: number;
  /** Number of input tokens consumed */
  inputTokens: number;
  /** Number of output tokens generated */
  outputTokens: number;
  /** Number of context tokens (from total input) */
  contextTokens: number;
  /** Number of tokens read from cache */
  cacheRead: number;
  /** Number of tokens written to cache */
  cacheWrite: number;
}
