/**
 * Type definitions for the OpenCode Prompt Recorder Plugin
 * Defines data structures used for tracking conversation metadata and logging
 */

/**
 * Represents a single assistant message step within a session.
 * In agent workflows, multiple steps may complete within one session.
 */
export interface MessageStep {
  /** Step number within the session (1-based) */
  stepNumber: number;
  /** Unique identifier for this assistant message */
  messageID: string;
  /** Agent name for this step (e.g., 'oracle', 'build') */
  agent: string;
  /** Model used for this step (e.g., 'opencode/hy3-preview-free') */
  model: string;
  /** Formatted time string (HH:MM:SS) when this step completed */
  time: string;
  /** Duration of this step in seconds */
  duration: string;
  /** Brief task description extracted from assistant output (first line, truncated to 120 chars) */
  taskDescription: string;
  /** Total tokens = input + output */
  totalTokens: number;
  /** Input tokens consumed by this step (includes cached portions) */
  inputTokens: number;
  /** Output tokens generated by this step */
  outputTokens: number;
  /** Cached tokens = cacheRead + cacheWrite (subset of inputTokens) */
  cachedTokens: number;
  /** Uncached tokens = inputTokens - cachedTokens */
  uncachedTokens: number;
  /** Cache read tokens (hit cached prompt, billed at discount) */
  cacheRead: number;
  /** Cache write tokens (first-time cache write, billed at premium) */
  cacheWrite: number;
}

/**
 * Represents the state of a conversation session
 * Captured when user sends a message, stored until assistant response completes
 */
export interface SessionState {
  /** Unique identifier for the user's message in this session */
  userMsgID: string;
  /** The prompt/input text from the user */
  prompt: string;
  /** AI model identifier (e.g., 'opencode/hy3-preview-free') */
  model: string;
  /** Unix timestamp (ms) when the session started */
  startTime: number;
  /** Array of agent names representing the call chain (e.g., ['main', 'oracle', 'build']) */
  agentChain: string[];
  /** Date string in 'YYYY-MM-DD' format, used for file naming */
  sessionStartTime: string;
  /** Set of assistant message IDs that have already been processed, to avoid double-counting */
  completedMessageIDs: Set<string>;
  /** Accumulated input tokens across all assistant messages in this session */
  totalInputTokens: number;
  /** Accumulated output tokens across all assistant messages in this session */
  totalOutputTokens: number;
  /** Accumulated context tokens across all assistant messages in this session */
  totalContextTokens: number;
  /** Accumulated cache read tokens across all assistant messages in this session */
  totalCacheRead: number;
  /** Accumulated cache write tokens across all assistant messages in this session */
  totalCacheWrite: number;
  /** Model from the most recent assistant message (may differ from initial model in agent chains) */
  lastModel: string;
  /** Whether at least one assistant message has completed (used to avoid writing empty logs) */
  hasCompletedMessage: boolean;
  /** Number of completed steps so far */
  stepCount: number;
  /** Whether the file header has been written for this session */
  headerWritten: boolean;
  /** Accumulated text content per messageID, collected from message.part.updated events */
  messageTexts: Map<string, string>;
}

/**
 * Configuration for billing - price per million tokens
 */
export interface BillingModelConfig {
  /** Full model name, must match the model field in markdown */
  model: string;
  /** Price per million input tokens (uncached) */
  input: number;
  /** Price per million output tokens */
  output: number;
  /** Price per million cache hit read tokens */
  cacheRead: number;
  /** Price per million cache hit write tokens */
  cacheWrite: number;
}

/**
 * Billing configuration section
 */
export interface BillingConfig {
  /** Master switch for billing feature */
  enabled: boolean;
  /** List of model pricing configurations */
  models: BillingModelConfig[];
}

/**
 * Main configuration for prompt recorder plugin
 */
export interface PromptRecorderConfig {
  /** Relative path from project root to output directory */
  outputPath: string;
  /** Prefix for generated markdown file names */
  filePrefix: string;
  /** Billing configuration */
  billing: BillingConfig;
}

/**
 * Cost breakdown for a step or session
 */
export interface CostBreakdown {
  /** Cost for uncached input tokens */
  inputCost: number;
  /** Cost for output tokens */
  outputCost: number;
  /** Cost for cached tokens (read + write) */
  cacheCost: number;
  /** Total cost */
  totalCost: number;
}

/**
 * Represents the summary log entry for a completed session
 * Written when session.idle fires, after all step logs have been written
 */
export interface LogData {
  /** Unique session identifier */
  sessionID: string;
  /** Formatted time string (HH:MM:SS) when conversation started */
  time: string;
  /** Agent call chain as arrow-separated string (e.g., 'oracle → build → explore') */
  agentChain: string;
  /** AI model identifier used for this conversation */
  model: string;
  /** User's original prompt text */
  prompt: string;
  /** Duration of conversation processing in seconds (fixed to 2 decimal places) */
  duration: string;
  /** Number of completed steps in this session */
  steps: number;
  /** Total tokens across all steps = totalInput + totalOutput */
  totalTokens: number;
  /** Number of input tokens consumed (includes cached portions) */
  inputTokens: number;
  /** Number of output tokens generated */
  outputTokens: number;
  /** Total cached tokens = totalCacheRead + totalCacheWrite (subset of inputTokens) */
  cachedTokens: number;
  /** Total uncached tokens = inputTokens - cachedTokens */
  uncachedTokens: number;
  /** Number of tokens read from cache */
  cacheRead: number;
  /** Number of tokens written to cache */
  cacheWrite: number;
  /** Optional cost breakdown (present when billing enabled and model matched) */
  costBreakdown?: CostBreakdown;
}
